#!/usr/bin/env python3
"""Generate a LaTeX document from full whisper transcript + key slides.

Aligns slide images with transcript text based on timestamps.
Each slide was extracted at fixed intervals; timestamps are
distributed proportionally across the video duration.

Usage:
    python3 gen_transcript_tex.py --base <project_dir> [--title "Title"] [--url "URL"] [--output transcript.tex]
"""

import argparse
import re
import os

from transcript_utils import build_slide_timestamps as _build_slide_timestamps
from transcript_utils import read_transcript as _read_transcript

SLIDE_TIMESTAMPS = {}

def build_slide_timestamps(base_dir, duration):
    """Build mapping: slide filename -> timestamp in seconds (delegates to shared module)."""
    slides, timestamps = _build_slide_timestamps(base_dir, duration)
    SLIDE_TIMESTAMPS.update(timestamps)
    return slides


def escape_tex(s):
    """Escape special LaTeX characters."""
    s = s.replace("\\", "\\textbackslash{}")
    s = s.replace("%", "\\%")
    s = s.replace("&", "\\&")
    s = s.replace("#", "\\#")
    s = s.replace("_", "\\_")
    s = s.replace("$", "\\$")
    s = s.replace("{", "\\{")
    s = s.replace("}", "\\}")
    s = s.replace("~", "\\textasciitilde{}")
    s = s.replace("^", "\\textasciicircum{}")
    return s


def read_transcript(base_dir, segment_sec=600):
    """Read the full whisper transcript (delegates to shared module)."""
    return _read_transcript(base_dir, segment_sec)


def generate_tex(paragraphs, slides, title="Video Transcript", url="", segment_sec=600):
    """Generate LaTeX document with transcript and slides interleaved."""
    slide_idx = 0
    tex = []

    # Determine section boundaries from paragraphs
    max_section = max(ts // segment_sec for ts, _ in paragraphs) if paragraphs else 0

    # Auto-generate section titles
    section_min = segment_sec // 60  # minutes per section
    section_titles = []
    for sec_idx in range(max_section + 1):
        start_min = sec_idx * section_min
        end_min = (sec_idx + 1) * section_min
        section_titles.append(f"Part {sec_idx + 1} ({start_min:02d}:00 -- {end_min:02d}:00)")

    # Preamble
    escaped_title = title.replace("&", "\\&").replace("_", "\\_")
    url_line = ""
    if url:
        url_line = f"  {{\\small 原始视频：\\href{{{url}}}{{{url}}}\\par}}"

    tex.append(r"""% transcript.tex
% Full verbatim transcript - auto-generated by gen_transcript_tex.py
% Compile: xelatex transcript.tex

\documentclass[11pt,a4paper]{article}

\usepackage{fontspec}
\usepackage{xeCJK}
\setCJKmainfont[BoldFont=PingFang SC Semibold]{PingFang SC}
\setCJKsansfont[BoldFont=PingFang SC Semibold]{PingFang SC}
\setCJKmonofont{PingFang SC}
\setmainfont{Palatino}
\setsansfont{Helvetica Neue}
\setmonofont{Menlo}

\usepackage[top=2.5cm, bottom=2.5cm, left=2.5cm, right=2.5cm]{geometry}
\usepackage{amsmath,amssymb}
\usepackage{graphicx}
\graphicspath{{images/}}
\usepackage{enumitem}
\usepackage{xcolor}
\usepackage{hyperref}
\usepackage{caption}
\hypersetup{
  colorlinks=true,
  linkcolor=blue!70!black,
  urlcolor=blue!70!black,
  pdfauthor={Whisper Transcription},
  pdftitle={""" + escaped_title + r"""},
}

\usepackage{parskip}
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}

\usepackage{mdframed}
\newmdenv[
  topline=false, bottomline=false, rightline=false,
  linewidth=3pt, linecolor=blue!40,
  innerleftmargin=12pt, innerrightmargin=12pt,
  innertopmargin=8pt, innerbottommargin=8pt,
  backgroundcolor=blue!3, skipabove=10pt, skipbelow=10pt,
]{myquote}

\usepackage{titlesec}
\titleformat{\section}{\Large\bfseries\sffamily}{}{0em}{}[\vspace{-0.5em}\rule{\textwidth}{0.5pt}]
\titleformat{\subsection}{\large\bfseries\sffamily}{}{0em}{}
\setcounter{secnumdepth}{0}

\setlength{\emergencystretch}{3em}
\tolerance=1000

\newcommand{\keyslide}[2]{%
  \begin{center}
    \includegraphics[width=0.88\textwidth]{#1}
    \captionof{figure}{#2}
  \end{center}
  \vspace{6pt}
}

\newcommand{\timestamp}[1]{%
  \hfill{\scriptsize\color{gray}[#1]}%
}

\begin{document}

\begin{titlepage}
  \centering
  \vspace*{3cm}
  {\Huge\bfseries\sffamily """ + escaped_title + r"""\par}
  \vspace{1.5cm}
  {\large\bfseries Full Verbatim Transcript\par}
  \vspace{0.3cm}
  {\small Transcribed by Whisper large-v3-turbo\par}
  \vspace{0.5cm}
""" + url_line + r"""
  \vfill
  {\large \today\par}
\end{titlepage}

\newpage
\tableofcontents
\newpage
""")

    current_section = -1

    for ts, para_text in paragraphs:
        new_section = min(ts // segment_sec, len(section_titles) - 1)

        if new_section != current_section:
            current_section = new_section
            tex.append(f"\n\\section{{{section_titles[current_section]}}}\n")

        # Insert slides whose timestamp is close to this paragraph
        while slide_idx < len(slides):
            slide_ts = SLIDE_TIMESTAMPS[slides[slide_idx]]
            if slide_ts <= ts + 15:
                slide_name = slides[slide_idx]
                slide_min = slide_ts // 60
                slide_sec = slide_ts % 60
                tex.append(f"\\keyslide{{{slide_name}}}{{Slide at {slide_min:02d}:{slide_sec:02d}}}\n")
                slide_idx += 1
            else:
                break

        t_min = ts // 60
        t_sec = ts % 60
        escaped = escape_tex(para_text)
        tex.append(f"{escaped} \\timestamp{{{t_min:02d}:{t_sec:02d}}}\n")

    # Insert remaining slides
    while slide_idx < len(slides):
        slide_name = slides[slide_idx]
        slide_ts = SLIDE_TIMESTAMPS[slides[slide_idx]]
        slide_min = slide_ts // 60
        slide_sec = slide_ts % 60
        tex.append(f"\\keyslide{{{slide_name}}}{{Slide at {slide_min:02d}:{slide_sec:02d}}}\n")
        slide_idx += 1

    tex.append("\n\\end{document}\n")
    return "\n".join(tex)


def main():
    parser = argparse.ArgumentParser(
        description="Generate LaTeX from whisper transcript + key slides."
    )
    parser.add_argument(
        "--base", "-b", required=True,
        help="Base project directory containing key_slides/ and full_whisper_transcript.txt"
    )
    parser.add_argument(
        "--title", "-T", default="Video Transcript",
        help="Document title for the PDF title page"
    )
    parser.add_argument(
        "--url", "-u", default="",
        help="Original video URL (shown on title page)"
    )
    parser.add_argument(
        "--duration", "-d", type=int, required=True,
        help="Video duration in seconds (passed from Makefile via ffprobe)"
    )
    parser.add_argument(
        "--segment-sec", "-s", type=int, default=600,
        help="Audio segment duration in seconds (default: 600, must match Makefile SEGMENT_SEC)"
    )
    parser.add_argument(
        "--output", "-o", default=None,
        help="Output .tex file path (default: <base>/publish_tex/transcript.tex)"
    )
    args = parser.parse_args()

    slides = build_slide_timestamps(args.base, args.duration)
    paragraphs = read_transcript(args.base, args.segment_sec)

    print(f"Paragraphs: {len(paragraphs)}")

    tex_content = generate_tex(paragraphs, slides, args.title, args.url, args.segment_sec)

    out_path = args.output or os.path.join(args.base, "publish_tex", "transcript.tex")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(tex_content)

    print(f"LaTeX written to {out_path}")
    print(f"Size: {len(tex_content)} bytes")


if __name__ == "__main__":
    main()
