#!/usr/bin/env python3
"""Convert structured Markdown slides to PPTX using python-pptx.

This is the "rendering layer" — it takes a structured slides.md
(generated by the LLM) and produces a polished .pptx file.

The LLM is responsible for the "content layer" — deciding what goes
on each slide, which images to include, and how to organize the content.

Expected Markdown format:
    # Presentation Title
    ## Slide Title
    - Bullet point 1
    - Bullet point 2
    ![caption](images/slide_0030.jpg)
    ---
    ## Next Slide Title
    ...

Usage:
    python3 md2pptx.py --input slides.md --output slides.pptx [--images images/]

Requirements:
    pip3 install python-pptx Pillow
"""

import argparse
import os
import re
import sys
from io import BytesIO

def check_dependencies():
    """Check if required Python packages are available."""
    missing = []
    try:
        import pptx
    except ImportError:
        missing.append("python-pptx")
    try:
        from PIL import Image
    except ImportError:
        missing.append("Pillow")
    if missing:
        print(f"ERROR: Missing Python packages: {', '.join(missing)}")
        print(f"Install: pip3 install {' '.join(missing)}")
        sys.exit(1)


def parse_slides(md_text):
    """Parse Markdown into a list of slide dicts.

    Each slide dict has:
        title:   str           — slide title (from ## heading)
        bullets: list[str]     — bullet points
        images:  list[dict]    — [{path, caption}, ...]
        notes:   str           — speaker notes (from > blockquote)
        is_title_slide: bool   — True if this is the presentation title (# heading)
    """
    slides = []
    current = None

    def flush():
        nonlocal current
        if current is not None:
            slides.append(current)
        current = None

    for line in md_text.splitlines():
        stripped = line.strip()

        # Title slide: # Presentation Title
        if re.match(r'^# [^#]', line):
            flush()
            current = {
                "title": line.lstrip("# ").strip(),
                "bullets": [],
                "images": [],
                "notes": "",
                "is_title_slide": True,
            }
            continue

        # Section/slide title: ## Slide Title
        if re.match(r'^## [^#]', line):
            flush()
            current = {
                "title": line.lstrip("# ").strip(),
                "bullets": [],
                "images": [],
                "notes": "",
                "is_title_slide": False,
            }
            continue

        # Subsection heading: ### Sub Title — treat as bold bullet
        if re.match(r'^### ', line):
            if current is None:
                current = {
                    "title": "",
                    "bullets": [],
                    "images": [],
                    "notes": "",
                    "is_title_slide": False,
                }
            current["bullets"].append("**" + line.lstrip("# ").strip() + "**")
            continue

        # Horizontal rule: slide separator (---, ___, ***)
        if re.match(r'^(-{3,}|_{3,}|\*{3,})$', stripped):
            # Only flush if we have content; otherwise ignore
            if current is not None and (current["bullets"] or current["images"]):
                flush()
            continue

        # Image: ![caption](path)
        img_match = re.match(r'!\[([^\]]*)\]\(([^)]+)\)', stripped)
        if img_match:
            if current is None:
                current = {
                    "title": "",
                    "bullets": [],
                    "images": [],
                    "notes": "",
                    "is_title_slide": False,
                }
            current["images"].append({
                "caption": img_match.group(1),
                "path": img_match.group(2),
            })
            continue

        # Bullet point: - text or * text or numbered list
        bullet_match = re.match(r'^[-*+]\s+(.+)', stripped)
        if not bullet_match:
            bullet_match = re.match(r'^\d+\.\s+(.+)', stripped)
        if bullet_match:
            if current is None:
                current = {
                    "title": "",
                    "bullets": [],
                    "images": [],
                    "notes": "",
                    "is_title_slide": False,
                }
            current["bullets"].append(bullet_match.group(1))
            continue

        # Blockquote: > speaker notes
        if stripped.startswith("> "):
            if current is not None:
                note_text = stripped[2:]
                current["notes"] += note_text + "\n"
            continue

        # Non-empty text that's not a heading/bullet — treat as bullet
        if stripped and current is not None:
            # Skip metadata lines like "Source:", "Author:" etc.
            current["bullets"].append(stripped)

    flush()
    return slides


def create_pptx(slides, output_path, images_dir=None, base_dir=None):
    """Create a PPTX file from parsed slide data."""
    from pptx import Presentation
    from pptx.util import Inches, Pt, Emu
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
    from PIL import Image

    prs = Presentation()
    # Set 16:9 aspect ratio
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Color scheme
    TITLE_COLOR = RGBColor(0x1A, 0x1A, 0x2E)  # Dark navy
    SUBTITLE_COLOR = RGBColor(0x4A, 0x90, 0xD9)  # Blue
    TEXT_COLOR = RGBColor(0x33, 0x33, 0x33)  # Dark gray
    ACCENT_COLOR = RGBColor(0x2C, 0x3E, 0x50)  # Slate
    BG_COLOR = RGBColor(0xFF, 0xFF, 0xFF)  # White

    def resolve_image_path(img_path):
        """Resolve image path relative to base directory."""
        if os.path.isabs(img_path):
            return img_path
        # Try relative to base_dir first
        if base_dir:
            candidate = os.path.join(base_dir, img_path)
            if os.path.exists(candidate):
                return candidate
        # Try relative to images_dir
        if images_dir:
            basename = os.path.basename(img_path)
            candidate = os.path.join(images_dir, basename)
            if os.path.exists(candidate):
                return candidate
        # Try as-is
        if os.path.exists(img_path):
            return img_path
        return None

    def add_image_to_slide(slide, img_path, left, top, max_width, max_height):
        """Add an image to a slide, maintaining aspect ratio."""
        resolved = resolve_image_path(img_path)
        if not resolved or not os.path.exists(resolved):
            print(f"  WARNING: Image not found: {img_path}")
            return
        try:
            with Image.open(resolved) as img:
                img_w, img_h = img.size
            aspect = img_w / img_h
            # Fit within max dimensions
            if max_width / max_height > aspect:
                height = max_height
                width = int(height * aspect)
            else:
                width = max_width
                height = int(width / aspect)
            # Center horizontally
            actual_left = left + (max_width - width) // 2
            slide.shapes.add_picture(resolved, actual_left, top, width, height)
        except Exception as e:
            print(f"  WARNING: Failed to add image {img_path}: {e}")

    def set_text_style(run, size=18, color=TEXT_COLOR, bold=False, italic=False):
        """Apply text styling to a run."""
        run.font.size = Pt(size)
        run.font.color.rgb = color
        run.font.bold = bold
        run.font.italic = italic

    for slide_data in slides:
        if slide_data["is_title_slide"]:
            # ── Title slide ──────────────────────────────────────────
            slide_layout = prs.slide_layouts[6]  # Blank layout
            slide = prs.slides.add_slide(slide_layout)

            # Background
            bg = slide.background
            fill = bg.fill
            fill.solid()
            fill.fore_color.rgb = RGBColor(0xF8, 0xF9, 0xFA)

            # Title text
            txBox = slide.shapes.add_textbox(
                Inches(1), Inches(2), Inches(11.333), Inches(2)
            )
            tf = txBox.text_frame
            tf.word_wrap = True
            p = tf.paragraphs[0]
            p.alignment = PP_ALIGN.CENTER
            run = p.add_run()
            run.text = slide_data["title"]
            set_text_style(run, size=36, color=TITLE_COLOR, bold=True)

            # Subtitle (first bullet if any)
            if slide_data["bullets"]:
                p2 = tf.add_paragraph()
                p2.alignment = PP_ALIGN.CENTER
                p2.space_before = Pt(20)
                run2 = p2.add_run()
                run2.text = slide_data["bullets"][0]
                set_text_style(run2, size=20, color=SUBTITLE_COLOR)

            # Add title image if present
            if slide_data["images"]:
                add_image_to_slide(
                    slide, slide_data["images"][0]["path"],
                    Inches(4), Inches(4.5), Inches(5.333), Inches(2.5)
                )

        else:
            # ── Content slide ────────────────────────────────────────
            slide_layout = prs.slide_layouts[6]  # Blank layout
            slide = prs.slides.add_slide(slide_layout)

            has_images = bool(slide_data["images"])
            has_bullets = bool(slide_data["bullets"])

            # Slide title bar
            title_box = slide.shapes.add_textbox(
                Inches(0.5), Inches(0.3), Inches(12.333), Inches(0.8)
            )
            tf_title = title_box.text_frame
            tf_title.word_wrap = True
            p_title = tf_title.paragraphs[0]
            run_title = p_title.add_run()
            run_title.text = slide_data["title"]
            set_text_style(run_title, size=28, color=TITLE_COLOR, bold=True)

            # Accent line under title
            from pptx.util import Inches as In
            line = slide.shapes.add_shape(
                1,  # MSO_SHAPE.RECTANGLE
                Inches(0.5), Inches(1.15), Inches(2), Pt(3)
            )
            line.fill.solid()
            line.fill.fore_color.rgb = SUBTITLE_COLOR
            line.line.fill.background()

            if has_images and has_bullets:
                # ── Two-column layout: text left, image right ────────
                # Text column
                text_box = slide.shapes.add_textbox(
                    Inches(0.5), Inches(1.5), Inches(6), Inches(5.5)
                )
                tf = text_box.text_frame
                tf.word_wrap = True

                for i, bullet in enumerate(slide_data["bullets"]):
                    p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
                    p.space_before = Pt(6)
                    p.space_after = Pt(4)

                    # Handle bold markers
                    if bullet.startswith("**") and bullet.endswith("**"):
                        run = p.add_run()
                        run.text = bullet.strip("*")
                        set_text_style(run, size=16, color=ACCENT_COLOR, bold=True)
                    else:
                        run = p.add_run()
                        run.text = "• " + bullet
                        set_text_style(run, size=14, color=TEXT_COLOR)

                # Image column (right side)
                img = slide_data["images"][0]
                add_image_to_slide(
                    slide, img["path"],
                    Inches(7), Inches(1.5), Inches(5.833), Inches(5)
                )

                # Additional images below (if any)
                for idx, img in enumerate(slide_data["images"][1:], 1):
                    if idx >= 2:
                        break  # Max 2 images per slide
                    add_image_to_slide(
                        slide, img["path"],
                        Inches(7), Inches(4), Inches(5.833), Inches(3)
                    )

            elif has_images and not has_bullets:
                # ── Full-width image slide ───────────────────────────
                img = slide_data["images"][0]
                add_image_to_slide(
                    slide, img["path"],
                    Inches(0.5), Inches(1.5), Inches(12.333), Inches(5.5)
                )

            elif has_bullets and not has_images:
                # ── Text-only slide ──────────────────────────────────
                text_box = slide.shapes.add_textbox(
                    Inches(0.5), Inches(1.5), Inches(12.333), Inches(5.5)
                )
                tf = text_box.text_frame
                tf.word_wrap = True

                for i, bullet in enumerate(slide_data["bullets"]):
                    p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
                    p.space_before = Pt(8)
                    p.space_after = Pt(4)

                    if bullet.startswith("**") and bullet.endswith("**"):
                        run = p.add_run()
                        run.text = bullet.strip("*")
                        set_text_style(run, size=18, color=ACCENT_COLOR, bold=True)
                    else:
                        run = p.add_run()
                        run.text = "• " + bullet
                        set_text_style(run, size=16, color=TEXT_COLOR)

        # Speaker notes
        if slide_data["notes"].strip():
            notes_slide = slide.notes_slide
            notes_slide.notes_text_frame.text = slide_data["notes"].strip()

    prs.save(output_path)
    print(f"PPTX written to {output_path}")
    print(f"Slides: {len(slides)}")
    print(f"Size: {os.path.getsize(output_path)} bytes")


def main():
    parser = argparse.ArgumentParser(
        description="Convert structured Markdown slides to PPTX presentation."
    )
    parser.add_argument(
        "--input", "-i", required=True,
        help="Input Markdown slides file (slides.md)"
    )
    parser.add_argument(
        "--output", "-o", required=True,
        help="Output PPTX file"
    )
    parser.add_argument(
        "--images", default=None,
        help="Images directory (for resolving relative image paths)"
    )
    args = parser.parse_args()

    check_dependencies()

    # Determine base directory from input file
    base_dir = os.path.dirname(os.path.abspath(args.input))

    with open(args.input, "r", encoding="utf-8") as f:
        md_text = f.read()

    slides = parse_slides(md_text)
    if not slides:
        print("ERROR: No slides found in input file.")
        print("Expected format: ## Slide Title followed by bullet points and/or images.")
        sys.exit(1)

    print(f"Parsed {len(slides)} slides from {args.input}")
    create_pptx(slides, args.output, images_dir=args.images, base_dir=base_dir)


if __name__ == "__main__":
    main()
